<?php

namespace Cacko\Yii2\Widgets\FullScreen;

use Cacko\Yii2\Widgets\FullScreen\components\Options;
use Yii;
use yii\helpers\Json;
use yii\web\AssetBundle;
use yii\web\JqueryAsset;
use yii\base\Widget;

class FullScreenAsset extends AssetBundle
{

    public $sourcePath = __DIR__ . DIRECTORY_SEPARATOR . 'assets' . DIRECTORY_SEPARATOR . 'fullscreen';

    public $js = [
        'js/widget.fullscreen.js',
    ];

    public $css = [
        'css/widget.fullscreen.scss',
        'css/widget-fullscreen-embedded.css',
    ];

    public $depends = [
        JqueryAsset::class,
    ];

    public static function register($view)
    {
        $options = Yii::createObject(Options::class);
        $view->registerJs(';$.fn.widgetFullScreen.defaults = ' . Json::encode($options) . ';');
        return parent::register($view);
    }

    public static function registerWidget(Widget $widget, Options $options): \yii\web\AssetBundle
    {
        $view = $widget->view;
        $widgetId = $widget->id;
        $options = Json::encode($options);

        $bundle = static::register($view); // TODO: Change the autogenerated stub
        $view->registerJs(sprintf("$('#%s').widgetFullScreen(%s);", $widgetId, $options));

        return $bundle;
    }
}
